#!/bin/busybox sh
/bin/busybox hostname $(/bin/busybox cat /etc/hostname)
export PATH="$PATH:/usr/bin:/bin:/usr/sbin:/sbin"

#/bin/busybox mkdir -p /usr/bin \
#        /usr/sbin \
#        /proc \
#        /sys \
#        /dev \
#        /media/cdrom \
#        /media/usb \
#        /tmp \
#        /etc \
#        /run/cryptsetup

/bin/busybox --install -s

mount -t sysfs -o noexec,nosuid,nodev sysfs /sys
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs -o exec,nosuid,mode=0755,size=2M devtmpfs /dev 2>/dev/null \
        ||  mount -t tmpfs -o exec,nosuid,mode=0755,size=2M tmpfs /dev
mkdir /dev/pts
mount -t devpts pts /dev/pts
chmod 1777 /tmp
setcap 'cap_sys_tty_config+ep' /bin/fbterm_real

modprobe usbcore e1000

if [ -f /sys/devices/platform/QEMUVGID:00/modalias ];then
        echo "Running inside QEMU. Loading modules"
        find /lib/modules/ -type f -name  \*virtio\* -exec bash -c 'modprobe $(basename {} | cut -d'.' -f1)' \;
	modprobe bochs
	chmod 777 /dev/fb0
fi


echo 'Starting DHCP client detached'
ifconfig eth0 up
udhcpc -i eth0 &

init_automount
while true;do
        /sbin/agetty tty1
done
